### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [addingwell/kwanko-tag#1]
https://github.com/addingwell/kwanko-tag/blob/fd95f2195980c6fcbaa25afeab10ef977bd6b692/template.tpl#L202

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

(The above code should use encodeUriComponent).

**Comment by WFrancois** [comment]
Hey!

Thanks for the comment, I _think_ it should correctly call the `encodeUriComponent` function

In https://github.com/addingwell/kwanko-tag/blob/master/template.tpl#L159
```
function encodeUri(value) {
  value = value || '';
  return encodeUriComponent(value);
}
```

Though I do agree it's not the best name, might be best to rename to `safeEncodeUriComponent` or something like that.

**Comment by WFrancois** [comment]
I've just published a new release which rename the function: https://github.com/addingwell/kwanko-tag/releases/tag/1.0.1

**Comment by semisight** [comment]
Yup you're totally right, my bad.

Would you mind adding that call to the lines below?

https://github.com/addingwell/kwanko-tag/blob/e80a1562199f48705053a5f56ff65fc333c0f21c/template.tpl#L203-L206

Then we can move forward adding this template to the gallery.

**Comment by WFrancois** [comment]
> Would you mind adding that call to the lines below?
> 
> https://github.com/addingwell/kwanko-tag/blob/e80a1562199f48705053a5f56ff65fc333c0f21c/template.tpl#L203-L206

This is done in https://github.com/addingwell/kwanko-tag/releases/tag/1.0.2 ; thanks!

**Comment by semisight** [comment]
Looks good, thanks!
